// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifiant stable d'un bloc (ULID). Jamais réutilisé après suppression.
 */
export type BlockId = string;
