// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlockId } from "./BlockId";
import type { Node } from "./Node";

/**
 * Un bloc = un identifiant stable + un nœud (son contenu typé).
 */
export type Block = { id: BlockId, node: Node, };
