// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Run } from "./Run";

/**
 * Cellule de table : une suite de runs.
 */
export type Cell = { runs: Array<Run>, };
