// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Block } from "./Block";
import type { Meta } from "./Meta";

/**
 * Document complet : métadonnées + suite ordonnée de blocs.
 */
export type Document = { meta: Meta, blocks: Array<Block>, };
