// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Styles applicables à un [`Run`].
 */
export type Marks = { bold: boolean, italic: boolean, underline: boolean, strike: boolean, code: boolean, 
/**
 * URL absolue, ou `None`.
 */
link: string | null, 
/**
 * Couleur hex `#RRGGBB`, ou `None`.
 */
color: string | null, };
