// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Patch de marques : `None` = champ inchangé. Pour `link`/`color`, la
 * double-option distingue « inchangé » (`None`) de « effacé » (`Some(None)`).
 */
export type MarkPatch = { bold?: boolean, italic?: boolean, underline?: boolean, strike?: boolean, code?: boolean, 
/**
 * `None` = inchangé ; `Some(None)` = retirer le lien ; `Some(Some(url))` = poser.
 */
link?: string | null, 
/**
 * Idem `link` pour la couleur hex `#RRGGBB`.
 */
color?: string | null, };
