// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Cell } from "./Cell";
import type { Run } from "./Run";

/**
 * Contenu typé d'un bloc.
 */
export type Node = { "type": "Paragraph", runs: Array<Run>, } | { "type": "Heading", 
/**
 * `1..=6`
 */
level: number, runs: Array<Run>, } | { "type": "ListItem", ordered: boolean, 
/**
 * `0..=5`
 */
level: number, runs: Array<Run>, } | { "type": "Quote", runs: Array<Run>, } | { "type": "CodeBlock", lang: string | null, text: string, } | { "type": "Table", rows: Array<Array<Cell>>, } | { "type": "Image", src: string, alt: string, 
/**
 * Largeur en pourcentage de la colonne, optionnelle.
 */
width_pct: number | null, } | { "type": "PageBreak" };
