// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Block } from "./Block";
import type { BlockId } from "./BlockId";
import type { MarkPatch } from "./MarkPatch";
import type { Node } from "./Node";
import type { Run } from "./Run";

/**
 * Opération atomique. **1 variante ⇒ 1 outil Anthropic** (le `input_schema`
 * de l'outil = les champs de la variante).
 */
export type Op = { "op": "InsertBlock", at: number, block: Block, } | { "op": "DeleteBlock", id: BlockId, } | { "op": "MoveBlock", id: BlockId, to: number, } | { "op": "SetNode", id: BlockId, node: Node, } | { "op": "SetRuns", id: BlockId, runs: Array<Run>, } | { "op": "ApplyMark", id: BlockId, range: [number, number], mark: MarkPatch, } | { "op": "SetTableCell", id: BlockId, row: number, col: number, runs: Array<Run>, } | { "op": "SetMeta", title?: string, lang?: string, };
