// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Marks } from "./Marks";

/**
 * Segment de texte inline + ses styles.
 */
export type Run = { text: string, marks: Marks, };
